//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1labaa1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListOfClothes", ReplyAction="*")]
        WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesResponse GetListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddListOfClothes", ReplyAction="*")]
        WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesResponse AddListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditListOfClothes", ReplyAction="*")]
        WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesResponse EditListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesRequest request);
        
        // CODEGEN: Generating message contract since element name Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteListOfClothes", ReplyAction="*")]
        WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesResponse DeleteListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfClothesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfClothes", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesRequestBody Body;
        
        public GetListOfClothesRequest() {
        }
        
        public GetListOfClothesRequest(WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListOfClothesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description;
        
        public GetListOfClothesRequestBody() {
        }
        
        public GetListOfClothesRequestBody(string Id, string Name, string Amount, string Price, string Description) {
            this.Id = Id;
            this.Name = Name;
            this.Amount = Amount;
            this.Price = Price;
            this.Description = Description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfClothesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfClothesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesResponseBody Body;
        
        public GetListOfClothesResponse() {
        }
        
        public GetListOfClothesResponse(WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListOfClothesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.ArrayOfString GetListOfClothesResult;
        
        public GetListOfClothesResponseBody() {
        }
        
        public GetListOfClothesResponseBody(WindowsFormsApplication1labaa1.ServiceReference1.ArrayOfString GetListOfClothesResult) {
            this.GetListOfClothesResult = GetListOfClothesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListOfClothesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddListOfClothes", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesRequestBody Body;
        
        public AddListOfClothesRequest() {
        }
        
        public AddListOfClothesRequest(WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddListOfClothesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description;
        
        public AddListOfClothesRequestBody() {
        }
        
        public AddListOfClothesRequestBody(string Id, string Name, string Amount, string Price, string Description) {
            this.Id = Id;
            this.Name = Name;
            this.Amount = Amount;
            this.Price = Price;
            this.Description = Description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListOfClothesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddListOfClothesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesResponseBody Body;
        
        public AddListOfClothesResponse() {
        }
        
        public AddListOfClothesResponse(WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddListOfClothesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddListOfClothesResult;
        
        public AddListOfClothesResponseBody() {
        }
        
        public AddListOfClothesResponseBody(int AddListOfClothesResult) {
            this.AddListOfClothesResult = AddListOfClothesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditListOfClothesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditListOfClothes", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesRequestBody Body;
        
        public EditListOfClothesRequest() {
        }
        
        public EditListOfClothesRequest(WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditListOfClothesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description;
        
        public EditListOfClothesRequestBody() {
        }
        
        public EditListOfClothesRequestBody(string Id, string Name, string Amount, string Price, string Description) {
            this.Id = Id;
            this.Name = Name;
            this.Amount = Amount;
            this.Price = Price;
            this.Description = Description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditListOfClothesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditListOfClothesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesResponseBody Body;
        
        public EditListOfClothesResponse() {
        }
        
        public EditListOfClothesResponse(WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditListOfClothesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EditListOfClothesResult;
        
        public EditListOfClothesResponseBody() {
        }
        
        public EditListOfClothesResponseBody(int EditListOfClothesResult) {
            this.EditListOfClothesResult = EditListOfClothesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteListOfClothesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteListOfClothes", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesRequestBody Body;
        
        public DeleteListOfClothesRequest() {
        }
        
        public DeleteListOfClothesRequest(WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteListOfClothesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description;
        
        public DeleteListOfClothesRequestBody() {
        }
        
        public DeleteListOfClothesRequestBody(string Id, string Name, string Amount, string Price, string Description) {
            this.Id = Id;
            this.Name = Name;
            this.Amount = Amount;
            this.Price = Price;
            this.Description = Description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteListOfClothesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteListOfClothesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesResponseBody Body;
        
        public DeleteListOfClothesResponse() {
        }
        
        public DeleteListOfClothesResponse(WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteListOfClothesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteListOfClothesResult;
        
        public DeleteListOfClothesResponseBody() {
        }
        
        public DeleteListOfClothesResponseBody(int DeleteListOfClothesResult) {
            this.DeleteListOfClothesResult = DeleteListOfClothesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap>, WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesResponse WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap.GetListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesRequest request) {
            return base.Channel.GetListOfClothes(request);
        }
        
        public WindowsFormsApplication1labaa1.ServiceReference1.ArrayOfString GetListOfClothes(string Id, string Name, string Amount, string Price, string Description) {
            WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesRequest inValue = new WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesRequest();
            inValue.Body = new WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Amount = Amount;
            inValue.Body.Price = Price;
            inValue.Body.Description = Description;
            WindowsFormsApplication1labaa1.ServiceReference1.GetListOfClothesResponse retVal = ((WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap)(this)).GetListOfClothes(inValue);
            return retVal.Body.GetListOfClothesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesResponse WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap.AddListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesRequest request) {
            return base.Channel.AddListOfClothes(request);
        }
        
        public int AddListOfClothes(string Id, string Name, string Amount, string Price, string Description) {
            WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesRequest inValue = new WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesRequest();
            inValue.Body = new WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Amount = Amount;
            inValue.Body.Price = Price;
            inValue.Body.Description = Description;
            WindowsFormsApplication1labaa1.ServiceReference1.AddListOfClothesResponse retVal = ((WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap)(this)).AddListOfClothes(inValue);
            return retVal.Body.AddListOfClothesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesResponse WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap.EditListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesRequest request) {
            return base.Channel.EditListOfClothes(request);
        }
        
        public int EditListOfClothes(string Id, string Name, string Amount, string Price, string Description) {
            WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesRequest inValue = new WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesRequest();
            inValue.Body = new WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Amount = Amount;
            inValue.Body.Price = Price;
            inValue.Body.Description = Description;
            WindowsFormsApplication1labaa1.ServiceReference1.EditListOfClothesResponse retVal = ((WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap)(this)).EditListOfClothes(inValue);
            return retVal.Body.EditListOfClothesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesResponse WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap.DeleteListOfClothes(WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesRequest request) {
            return base.Channel.DeleteListOfClothes(request);
        }
        
        public int DeleteListOfClothes(string Id, string Name, string Amount, string Price, string Description) {
            WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesRequest inValue = new WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesRequest();
            inValue.Body = new WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Amount = Amount;
            inValue.Body.Price = Price;
            inValue.Body.Description = Description;
            WindowsFormsApplication1labaa1.ServiceReference1.DeleteListOfClothesResponse retVal = ((WindowsFormsApplication1labaa1.ServiceReference1.WebService1Soap)(this)).DeleteListOfClothes(inValue);
            return retVal.Body.DeleteListOfClothesResult;
        }
    }
}
